## Exercice 9 p. 67

In [5]:
table1 = [('id_exp',  'T' , 'tps'),
          (    1   , 20.2 ,  56  ),
          (    2   , 15.5 ,  85  ),
          (    3   , 18.6 , 120  )]

In [6]:
table2 = [('id_exp',  'T' , 'tps'),
          (    1   , 53.6 , 210  ),
          (    2   , 62.6 ,  81  ),
          (    3   , 66.2 ,  70  )]

In [ ]:
def fusion(t1,t2):
    """fusionne t1 et t2
    en renumérottant les expériences de t2
    et en convertissant les températures de t2 en degrés Celsius"""
    
    return